server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React router — serve index.html for all routes so client-side routing works
    location / {
        try_files $uri $uri/ /index.html;
    }
}
